apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  labels:
    app: todoapp
spec:
  containers:
  - name: mysql
    image: mysql:8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: tododb
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
  - name: todoapp
    image: rameshkumar13111/todoapp:lates
    ports:
    - containerPort: 8080
    env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://localhost:3306/tododb
    - name: SPRING_DATASOURCE_USERNAME
      value: myuser
    - name: SPRING_DATASOURCE_PASSWORD
      value: user123
  volumes:
  - name: mysql-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
