version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp
    image: todoapp:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/todoapp
      SPRING_DATASOURCE_USERNAME: myuser             
      SPRING_DATASOURCE_PASSWORD: user123
    networks:
      - mynetwork

#  mysqldb:
#    image: mysql:8.0
#    container_name: mysql-container
#    networks:
#      - mynetwork
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: yes
#      MYSQL_DATABASE: todoapp
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: user123
#    volumes:
#       - "c:/mysql_data:/var/lib/mysql"

networks:
  mynetwork:
    driver: bridge
