version: '3.8'

services:
  springboot:
    build:
    
  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
    ports:
      - "3306:3306"
    volumes:
      - c:/mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
