version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/todoapp
      SPRING_DATASOURCE_USERNAME: myuser             
      SPRING_DATASOURCE_PASSWORD: user123

  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123   # ✔️ सिर्फ ये चाहिए root के लिए
      MYSQL_DATABASE: todoapp           # (optional) default DB create करेगा
      MYSQL_USER: myuser             # ✔️ नया user (root नहीं)
      MYSQL_PASSWORD: user123        # ✔️ उस user का password
    volumes:
       - "c:/mysql_data:/var/lib/mysql"   # ✅ Named volume

